COMP: Use override instead of old ITK macro ITK_OVERRIDE
The error message was:

C:\Dev\ITK-git\Modules\Remote\Shape\include\itkMeshProcrustesAlignFilter.h(203,70): error C2143: syntax error: missing ';' before 'static_assert'